name: "Build and test main branch"

on:
  push:
    paths:
      - '**/com/tease/androidactionstest/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build android app, run tests and pull apk to releases
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: 'set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "prepare NDK dir for caching (workaround for https://github.com/actions/virtual-environments/issues/1337)"
        run: |
          sudo mkdir -p ${ANDROID_HOME}/ndk
          sudo chmod -R 777 ${ANDROID_HOME}/ndk
          sudo chown -R $USER:$USER ${ANDROID_HOME}/ndk

      - name: "NDK Cache"
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: ${ANDROID_HOME}/ndk
          key: ndk-cache-21.2.6472646-v2

      - name: "install NDK"
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.2.6472646"

      - name: 'cache gradle packages'
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: 'clean, test, build and publish'
        run: ./gradlew clean check jacocoTestCoverageVerification assemble
        env:
          COVERAGE_LIMIT: 0.3
          GITHUB_USER: vlas-ilya
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.token }}

      - name: 'publish'
        run: ./gradlew app:publishMavenReleaseApkPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: vlas-ilya
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.token }}

      - name: 'show test report in logs'
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: 'publish test report'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: app/build/reports/tests/testDebugUnitTest/*

      - name: 'publish test coverage report'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-coverage-report'
          path: app/build/reports/jacoco/generateJacocoTestReports/html/*